keep:
  db: common_data


spring:
  profiles:
    active: local
server:
  port: 8001
---
spring:
  profiles: local
  datasource:
    schema: classpath*:configuration/local/schema.sql
    data: classpath*:configuration/local/data.sql
    initialization-mode: always
logging:
  level:
    root: info
    com.master: debug
    spring.jiminshiro.mapper: debug